"""Generate synthesis-ready specifications for top IDP antibody candidates."""
import json, os
from pathlib import Path

# ── 4HIX (Abeta) candidates ──
VH_PRE = 'VQLLESGGGLVQPGGSLRLSCAASGFTFSNYGMSWVRQAPGKGLEWVASIRSGGGRTYYSDNVKGRFTISRDNAKNSLYLQMNSLRAEDTALYYCV'
VH_POST = 'WGQGTLVTVSS'
VL_4HIX = 'YVVMTQSPLSLPVTPGEPASISCKSSQSLLDSDGKTYLNWLLQKPGQSPQRLIYLVSKLDSGVPDRFSGSGSGTDFTLKISRVEAEDVGVYYCWQGTHFPRTFGQGTKVEIKR'

# Top 5 4HIX designs from AF2 validation
DESIGNS_4HIX = [
    ('4HIX-D1', 'LYDESKDAESE', 0.4615),
    ('4HIX-D2', 'LYDAHHGAHSL', 0.4611),
    ('4HIX-D3', 'LYDGSIGAESQ', 0.4598),
    ('4HIX-D4', 'LYDSSVDASGH', 0.4592),
    ('4HIX-D5', 'LFNEANCAESY', 0.4584),
]
NATIVE_4HIX = ('4HIX-Native', 'VRYDHYSGSSDY', 0.4491)

out = []
out.append("# IDP Antibody Design — Synthesis Specifications")
out.append("")
out.append("## Target: Abeta (1-42) — DAEFRH epitope")
out.append("## Scaffold: 4HIX (humanized 3D6 Fab)")
out.append("")
out.append(f"Native CDR-H3: {NATIVE_4HIX[1]}  (AF2 ipTM: {NATIVE_4HIX[2]:.4f})")
out.append("")
out.append("### Top 5 Designed CDR-H3 Sequences")
out.append("")
out.append("| ID | H3 Sequence | AF2 ipTM | Δ vs Native | Full VH Length |")
out.append("|---|---|---|---|---|")
out.append(f"| Native | {NATIVE_4HIX[1]} | {NATIVE_4HIX[2]:.4f} | — | {len(VH_PRE+NATIVE_4HIX[1]+VH_POST)} |")
for did, h3, iptm in DESIGNS_4HIX:
    out.append(f"| {did} | {h3} | {iptm:.4f} | {iptm-NATIVE_4HIX[2]:+.4f} | {len(VH_PRE+h3+VH_POST)} |")
out.append("")

out.append("### Full VH Sequences for Gene Synthesis")
out.append("")
for did, h3, iptm in DESIGNS_4HIX:
    full_vh = VH_PRE + h3 + VH_POST
    out.append(f"**{did}** (H3={h3}, AF2 ipTM={iptm:.4f})")
    out.append(f"```")
    out.append(full_vh)
    out.append(f"```")
    out.append("")

out.append("### Light Chain (constant across all designs)")
out.append("```")
out.append(VL_4HIX)
out.append("```")
out.append("")

out.append("### Ordering Information")
out.append("- **Format**: scFv or Fab, VH-VL with (G4S)3 linker for scFv")
out.append("- **Expression**: HEK293 or E. coli (periplasmic)")
out.append("- **Purification**: Protein A/G (Fab) or His-tag (scFv)")
out.append("- **Validation**: AF2 multimer ipTM > 0.45 for all designs")
out.append("- **Epitope**: DAEFRH peptide (Abeta 1-6), extendable to Abeta 1-42")
out.append("")
out.append("### Controls")
out.append("- **Positive**: 4HIX Native (VRYDHYSGSSDY) — known binder, AF2 ipTM 0.449")
out.append("- **Negative**: Scrambled H3 (shuffle native H3 residues)")
out.append("- **Blank**: scFv without CDR-H3 (framework only)")
out.append("")

# ── Tau candidates ──
out.append("---")
out.append("")
out.append("## Target: Tau (5MP3 complex, 9-residue epitope)")
out.append("## Scaffold: 5MP3 Fab")
out.append("")
out.append("ProteinMPNN designed CDR-H3 sequences (10 samples, T=0.5).")
out.append("AF2 validation pending — sequences provided for preliminary screening.")
out.append("")
out.append("| ID | MPNN Score |")
out.append("|---|---|")
if os.path.exists('idp_design_results/tau_5MP3_results.json'):
    tau = json.load(open('idp_design_results/tau_5MP3_results.json'))
    for d in tau['designs'][:5]:
        out.append(f"| tau-{d['sample']:02d} | {d['score']:.3f} |")

# ── Alpha-synuclein candidates ──
out.append("")
out.append("---")
out.append("")
out.append("## Target: Alpha-Synuclein (8B9V complex, 10-residue epitope)")
out.append("## Scaffold: 8B9V Fab")
out.append("")
out.append("| ID | MPNN Score |")
out.append("|---|---|")
if os.path.exists('idp_design_results/alpha_syn_8B9V_results.json'):
    syn = json.load(open('idp_design_results/alpha_syn_8B9V_results.json'))
    for d in syn['designs'][:5]:
        out.append(f"| syn-{d['sample']:02d} | {d['score']:.3f} |")

out.append("")
out.append("---")
out.append("*Generated by DisorderFlow IDP antibody design pipeline*")
out.append("*ProteinMPNN v_48_020 + AF2 multimer V3 validation*")

report = '\n'.join(out)
Path('idp_design_results').mkdir(exist_ok=True)
with open('idp_design_results/SYNTHESIS_SPECS.md', 'w') as f:
    f.write(report)
print(report[:3000])
print(f"\nSaved: idp_design_results/SYNTHESIS_SPECS.md")
